name: Daily Reminder

on:
  schedule:
    # 11:37 PM CST = 4:37 AM UTC next day (during DST) or 5:37 AM UTC (standard time)
    # Using 4:37 AM UTC
    - cron: '37 4 * * *'

  workflow_dispatch:

jobs:
  send-reminder:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm ci

      - name: Send daily reminder
        env:
          PUMBLE_API_KEY: ${{ secrets.PUMBLE_API_KEY }}
        run: |
          echo "Sending daily reminder at $(date)"
          node scripts/send-message.js -c bot-testing -m "Daily Message check from GitHub Actions"