name: Monday Pay Period Reminder

on:
  schedule:
    # Run every Monday at 12 PM CST (5 PM UTC during DST, 6 PM UTC during standard time)
    # Matching Koyeb configuration
    - cron: '0 17 * * 1'
    
  workflow_dispatch:
    inputs:
      test_mode:
        description: 'Run in test mode (bypasses date check)'
        required: false
        default: 'false'
        type: boolean
      action:
        description: 'Which action to run'
        required: false
        default: 'both'
        type: choice
        options:
          - 'both'          # Send advance notice + main reminders
          - 'advance-only'  # Only send advance notice to Mikhail
          - 'main-only'     # Only send main reminders to channels

jobs:
  send-reminders:
    # Run on schedule or when manually triggered
    if: github.event_name == 'schedule' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
    
    - name: Install dependencies
      run: |
        npm install
    
    - name: Send Monday Reminders
      env:
        PUMBLE_API_KEY: ${{ secrets.PUMBLE_API_KEY }}
        
      run: |
        echo "📅 Monday reminder check at $(date)"

        # Check if we're in the monday-reminder directory structure
        if [ -d "monday-reminder" ]; then
          cd monday-reminder
          node monday-reminder.js send
        else
          # Use the new scripts structure (matching Koyeb)
          echo "Sending to dev channel..."
          node scripts/send-timesheet-reminder.js -c dev

          echo "Sending to design channel..."
          node scripts/send-timesheet-reminder.js -c design
        fi