name: Test Cron 5 Minutes

on:
  schedule:
    # Run at 8:15 AM CST (1:15 PM UTC)
    - cron: '15 13 * * *'
    
  workflow_dispatch:

jobs:
  test-reminder:
    runs-on: ubuntu-latest
    
    steps:
    - name: Test Echo
      run: |
        echo "🔔 Test cron triggered at $(date)"
        echo "This workflow is running!"
        
    - name: Checkout code
      uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '22'
    
    - name: Install dependencies
      run: |
        npm install
    
    - name: Send Test Reminder to Mikhail DM
      env:
        PUMBLE_API_KEY: ${{ secrets.PUMBLE_API_KEY }}
        
      run: |
        echo "🔔 Running test cron job..."
        node scripts/send-message.js -c bot-testing -m "Test cron job executed successfully at $(date +%H:%M) CST"